"""empty message

Revision ID: 44a54a232500
Revises: d70bdf57e5dd
Create Date: 2024-08-04 17:20:34.043269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44a54a232500'
down_revision = 'd70bdf57e5dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('advertisement', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('date_posted', sa.DateTime(), nullable=False))
    #     batch_op.alter_column('image_file',
    #            existing_type=sa.VARCHAR(length=120),
    #            type_=sa.String(length=20),
    #            existing_nullable=True)

    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('advertisement', schema=None) as batch_op:
    #     batch_op.alter_column('image_file',
    #            existing_type=sa.String(length=20),
    #            type_=sa.VARCHAR(length=120),
    #            existing_nullable=True)
    #     batch_op.drop_column('date_posted')

    pass

    # ### end Alembic commands ###
