"""empty message

Revision ID: d70bdf57e5dd
Revises: e7d8046abdae
Create Date: 2024-08-04 17:18:57.064836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd70bdf57e5dd'
down_revision = 'e7d8046abdae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # The following operations are ignored
    # with op.batch_alter_table('advertisement', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('embed_link', sa.String(length=255), nullable=True))
    #     batch_op.alter_column('image_file',
    #            existing_type=sa.VARCHAR(length=20),
    #            type_=sa.String(length=120),
    #            existing_nullable=True)
    #     batch_op.drop_column('date_posted')

    pass  # Ignore operations

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # The following operations are ignored
    # with op.batch_alter_table('advertisement', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('date_posted', sa.DATETIME(), nullable=False))
    #     batch_op.alter_column('image_file',
    #            existing_type=sa.String(length=120),
    #            type_=sa.VARCHAR(length=20),
    #            existing_nullable=True)
    #     batch_op.drop_column('embed_link')

    pass  # Ignore operations

    # ### end Alembic commands ###
