"""empty message

Revision ID: e285c577f59a
Revises: 4ad2b190b1d2
Create Date: 2024-08-04 19:13:10.169206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e285c577f59a'
down_revision = '4ad2b190b1d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advertisement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('views', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('clicks', sa.Integer(), nullable=True))
        batch_op.alter_column('date_posted',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advertisement', schema=None) as batch_op:
        batch_op.alter_column('date_posted',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('clicks')
        batch_op.drop_column('views')

    # ### end Alembic commands ###
